 "use client";
import {useEffect,useMemo,useState} from "react";
import {Activity,BarChart3,Bot,ChevronRight,Clock3,Home,RefreshCw,Trophy} from "lucide-react";
import Link from "next/link";

type Match={id:string;name:string;status:string;state:string;venue?:string;teams?:string[];score?:any[];start_time?:string;format?:string;matchStarted?:boolean;matchEnded?:boolean};
const tabs=[["home","Home",Home],["live","Live",Activity],["series","Series",Trophy],["ai","AI",Bot]] as const;

export default function HomePage(){
 const [matches,setMatches]=useState<Match[]>([]); const [tab,setTab]=useState("home"); const [loading,setLoading]=useState(true); const [question,setQuestion]=useState(""); const [answer,setAnswer]=useState(""); const [asking,setAsking]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await fetch("/api/matches",{cache:"no-store"});const d=await r.json();setMatches(d.matches||[])}finally{setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[]);
 const live=useMemo(()=>matches.filter(m=>m.state==="Live"),[matches]);
 const upcoming=useMemo(()=>matches.filter(m=>m.state==="Upcoming"),[matches]);
 async function ask(){if(!question.trim())return;setAsking(true);try{const r=await fetch("/api/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:question})});const d=await r.json();setAnswer(d.answer||d.error||"No answer")}finally{setAsking(false)}}
 return <main className="shell"><header className="topbar"><div className="container" style={{padding:"0"}}><div className="brand"><span className="brandmark">🏏</span>CricAI <span className="subtle">LIVE INTELLIGENCE</span></div></div></header>
 <div className="container">
  <section className="hero"><div className="subtle" style={{color:"#a5b4fc"}}>YOUR CRICKET CENTRE</div><h1>Every ball. Smarter.</h1><p>Live scores, ball-by-ball, odds, fancy and AI-powered match analysis.</p><div className="chips"><button className={`chip ${tab==="home"?"active":""}`} onClick={()=>setTab("home")}>All</button><button className={`chip ${tab==="live"?"active":""}`} onClick={()=>setTab("live")}>🔴 Live {live.length||""}</button><button className="chip" onClick={load}><RefreshCw size={14} style={{verticalAlign:"-2px"}}/> Refresh</button></div></section>
  {tab==="ai"?<section className="section"><div className="sectionhead"><h2>Ask CricAI</h2><Bot size={19}/></div><div className="panel"><p className="subtle">Ask about the current matches, score trends, pitch notes or team momentum. CricAI uses only the live data available in the system.</p><div className="chat"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")ask()}} placeholder="e.g. Who has momentum right now?"/><button onClick={ask} disabled={asking}>{asking?"…":"Ask"}</button></div>{answer&&<div className="panel" style={{marginTop:12,background:"transparent"}}>{answer}</div>}</div></section>:<><section className="section"><div className="sectionhead"><h2>{tab==="live"?"Live matches":"Live now"}</h2><span className="subtle">{live.length} matches</span></div><div className="cards">{loading?<div className="empty">Loading live cricket…</div>:live.length?live.map(m=><MatchCard key={m.id} m={m}/>):<div className="empty"><Activity size={28}/><br/>No live matches right now.</div>}</div></section>
  {tab!=="live"&&<section className="section"><div className="sectionhead"><h2>Upcoming</h2><span className="subtle">{upcoming.length} matches</span></div><div className="cards">{upcoming.slice(0,8).map(m=><MatchCard key={m.id} m={m}/>)}{!upcoming.length&&!loading&&<div className="empty">Fixtures will appear here as the sync runs.</div>}</div></section>}
  {tab!=="live"&&<section className="section"><div className="grid2"><div className="panel"><BarChart3 size={20}/><div className="metric">Live Odds</div><div className="subtle">Match odds and market snapshots when available.</div></div><div className="panel"><Bot size={20}/><div className="metric">AI Match IQ</div><div className="subtle">Momentum, wickets, pitch and player insights.</div></div></div></section>}</>}
 </div>
 <nav className="bottom"><div className="nav">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={18}/><br/>{label}</button>)}</div></nav></main>
}
function MatchCard({m}:{m:Match}){return <Link href={`/match/${m.id}`} className="match"><div className="matchtop"><div><b>{m.format||"Cricket"}</b><div className="subtle">{m.venue||"Venue TBC"}</div></div><span className={`status ${m.state==="Live"?"live":""}`}>{m.state==="Live"?"● LIVE":m.state}</span></div><div className="teams">{(m.teams||["Team A","Team B"]).map((t,i)=><div className="teamrow" key={t}><span className="teamname">{t}</span><span className="score">{m.score?.[i]?.runs!=null?`${m.score[i].runs}/${m.score[i].wickets||0}`:"—"}</span></div>)}</div><div className="meta"><span><Clock3 size={12} style={{verticalAlign:"-2px"}}/> {m.start_time?new Date(m.start_time).toLocaleString():"Time TBC"}</span><span>Match Centre <ChevronRight size={13} style={{verticalAlign:"-2px"}}/></span></div></Link>}
